services:
  crawlserver:
    build: .
    container_name: crawlserver
    ports:
      - ${CRAWL_SERVER_PORT}:${CRAWL_SERVER_PORT}
    # volumes:
    #   - ./:/app
    env_file:
      - .env.docker
    command: ["npm", "run", "start"]
  
  cron:
    build: .
    container_name: cron
    # volumes:
    #   - ./:/app
    env_file:
      - .env.docker
    command: ["npm", "run", "cron"]